#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd
TMPOUT='_wsprd.out'

#fix simple() permission denied
pax11publish -d
pax11publish -r
##

decode () {

	date >> /home/elec3607/rev/lab5-audio/wsproutput.log
	./wsprcan/k9an-wsprd  >> /home/elec3607/rev/lab5-audio/wsproutput.log
	# sleep 118
}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')

	if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
		echo -n "Executing wspr_decode "
		decode
	elif ((10#$sec < 40)); then
		sleep 1
	fi
done
